version: '3'
services:
  fish:
    build:
      context: .
      dockerfile: Dockerfile-App
    image: fishsim-compose:latest
    container_name: fish
    command: ["developer_scripts/./wait_for_http_service_and_run_cmd.sh", "mongo-fish:27017", "3", "2", "npm", "start"]
    depends_on:
      - mongo-fish
    volumes:
      - .:/fish/app
    ports:
      - "8080:80"
  mongo-fish:
    build:
      context: .
      dockerfile: Dockerfile-Db
    image: mongofish-compose:latest
    container_name: mongo-fish
    volumes:
      - ./mongo.log:/logs/mongo.log
